### ISSUE TITLE
Switch to conventional changelog 

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#102]
We need to document the conventions properly 😏

**Comment by mischah** [comment]
@krnlde Cant find them 😂

Seems to be plugin based. The organisation offers different presets:
- https://github.com/conventional-changelog/conventional-changelog-eslint
- https://github.com/conventional-changelog/conventional-changelog-angular
- https://github.com/conventional-changelog/conventional-changelog-jquery
- etc.

But isn’t there something like a default preset?

Or is plugin based and you have t

**Comment by krnlde** [comment]
There is no default. I personally use the angular preset, which is in a way common sense. https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/convention.md

**Comment by mischah** [comment]
Made it to the `v4-dev` branch using the angular preset.
Trying to get the [conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md) in my head.

**Comment by krnlde** [comment]
If you need help with conventions talk to me.

**Comment by mischah** [comment]
Thanks. Just need to get used to it ☺️
