### ISSUE TITLE
Integrate gulp-envify for dependencies relying on process.env.NODE_ENV

### ISSUE THREAD

**Issue by revrng** [micromata/bootstrap-kickstart#155]
There are dependencies relying on `process.env.NODE_ENV`. Depending on whether `process.env.NODE_ENV` is set to `production` or not, e.g. redux is requiring other modules inside the source-code mainly for providing lots ot tooling/debugging features in dev mode. For a production build it's necessary to set `process.env.NODE_ENV`to `production` to get the optimized version for production. 

To achieve this we can use `gulp-envify` (https://github.com/tomashanacek/gulp-envify). It should be used only in the production build of the vendor scripts.

**Comment by krnlde** [comment]
I'd be very careful with gulp-envify. It only has 5 starts and was last updated a year ago. Plus I don't really get what the benefit is. Do we really need so much orchestration stuff?

**Comment by mischah** [comment]
> I'd be very careful with gulp-envify. It only has 5 starts and was last updated a year ago. 

It’s sets `NODE_ENV`. What could possibly go wrong?
Would you feel more comfortable using [envify](https://github.com/hughsk/envify)?

> Plus I don't really get what the benefit is. Do we really need so much orchestration stuff?

Like @revrng explained: 
There are dependencies which require a »correct« value for the environment variable `NODE_ENV`.

**Comment by mischah** [comment]
Excerpt from React docs for example:

>To use React in production mode, set the environment variable NODE_ENV to production. A minifier that performs dead-code elimination such as UglifyJS is recommended to completely remove the extra code present in development mode.

Means we would have a larger vendor bundle without setting `NODE_ENV` to `production`.
