### ISSUE TITLE
Loading "autoprefixer.js" tasks...ERROR >> Error: Cannot find module 'browserslist'

### ISSUE THREAD

**Issue by alisamii** [micromata/bootstrap-kickstart#16]
In fact, I get a whole bunch of errors when I run `grunt tasks` and the process aborts.

     ➜  grunt tasks
    Loading "autoprefixer.js" tasks...ERROR
    >> Error: Cannot find module 'browserslist'
    Loading "bootlint.js" tasks...ERROR
    >> Error: Cannot find module 'cheerio'
    Loading "plato.js" tasks...ERROR
    >> Error: Cannot find module 'plato'

    Running "availabletasks:tasks" (availabletasks) task
    Warning: Cannot set property 'info' of undefined Use --force to continue.

    Aborted due to warnings.

    Execution Time (2015-03-12 09:01:52 UTC)
    loading tasks         61ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 42%
    availabletasks:tasks  83ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 57%
    Total 145ms

Any ideas?

I installed Bootstrap Kickstart with `yo bootstrap-kickstart`

**Comment by krnlde** [comment]
Did you additionally `npm install` manually?

**Comment by mischah** [comment]
@alisamii 
It seems that soemthing went wrong with the installation.
I recently had problems with the installation too.

Please check if your `npm` version is up to date → `npm --v` should return `2.7.0`

Please try the following:

1. Delete the `node modules` directory in your project root
2.  Clean your npm cache with → `sudo npm cache clean`
1. Reinstall with super user privileges → `sudo npm install`

Paste your install log into this issue in case you still encounter problems.

Good luck :four_leaf_clover:

**Comment by mischah** [comment]
Close. Because this is not an issue with Bootstrap Kickstart or the Yeoman Generator.

@alisamii Feel free to drop me a line if you still have problems with the installation.

**Comment by hellboy81** [comment]
Have the same issue

**Comment by mischah** [comment]
@hellboy81 
mhhm. Did you encounter any issues while `npm install`?
If so, did you tried `npm cache clean` and reinstalling? Like mentioned above.

If you still have problems with running `grunt tasks` enter `grunt tasks --verbose` and paste the log over here.

**Comment by dmanzer2** [comment]
I had the same issue. Removed, cleaned cache, and updated everything to current versions. This worked like a champ! Thanks "mischah"!

**Comment by mischah** [comment]
@dmanzer2 Your welcome 😙

**Comment by irvash** [comment]
I did as mischah said still not working, there was no problem on npm install
anyone? Ideas?

**Comment by mischah** [comment]
Hej @irvash,

please paste your install log over here.
