### ISSUE TITLE
Linting LESS with stylelint

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#165]
# 1. We need to evaluate how it works with LESS.

Because the [README](https://github.com/stylelint/stylelint) says the following:

>  […] it understands any syntax that PostCSS can parse, including SCSS, SugarSS, and _experimental support for Less_.

# 2. We have to decide which rules to use with which setting.

It offers more than [150 rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md). Per default none is activated so one can switch on only a few if one wants to start small.

The other option is to use a shared config. [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) is maintained bei the maintainers of stylelint and includes over [80 of stylelint's rules](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js) with sensible defaults. This might be a good basis in case we would like to add stylistic rules to our ruleset.

Let’s discuss 🗣 

P.S. Here’s the [gulp plugin](https://github.com/olegskl/gulp-stylelint) btw.

**Comment by nicolaisueper** [comment]
I think we should start with the stylelint-config-standard and add/remove rules on demand.

**Comment by mischah** [comment]
> I think we should start with the stylelint-config-standard and add/remove rules on demand.

👍 Jep

**Comment by mischah** [comment]
Done in v4-dev branch 🎉
