### ISSUE TITLE
Question: Drop support for node < v6?

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#166]
What do you think about dropping support for node 4 as well as node 5?
That way we could use more ES6 in our gulp related files.

Example:
Using `Array.prototype.includes` could make checking thinks more beautiful:
https://github.com/micromata/bootstrap-kickstart/compare/6a267ee12684...ce678b257504

I reverted that change. Since `Array.prototype.includes` [is available since node v6 without `--harmony`](http://node.green/#ES2016-features-Array-prototype-includes).

**Can I get a thumb up or down for dropping support for node < v6?**

*Personal note:*
*At Yeoman we support Node down to the latest LTS version. Which means we dropped support for Node 0.12 recently and still support Node 4 which is the oldest still maintained LTS version right now.*

**Comment by mischah** [comment]
I need feedback: @micromata/ux @micromata/developers

**Comment by mischah** [comment]
@micromata/ux 

Last chance to drop support for node 4 and 5 with Bootstrap Kickstart v4. We are feature complete and have released to release candidates for now.

The next Chance to get rid of them is with Bootstrap Kickstart v5 which might take a while.

I’ll close this if the 👎  are dominating in a few days.

Thanks for your feedback 🌹

**Comment by krnlde** [comment]
Node 8 is coming end of this month and will replace 6 as LTS.

**Comment by mischah** [comment]
Jup. But: Maintenance of Node 4 will end in April 2018. See [Node LTS schedule](https://github.com/nodejs/LTS#lts-schedule1).

Must say that I see no reason to use that on a personal machine though 😏  … So I wouldn’t feel that bad with kicking it now even if it’s a bit early.

**Comment by krnlde** [comment]
Why the "👎"  then? :-P

**Comment by mischah** [comment]
😛 

Because I don’t feel l comfortable with kicking people out which are forced to use old versions. 
But I have no idea if there are any in our small user community. 👍 👎

**Comment by krnlde** [comment]
Why not? Apple and Adobe do this all the time ;) Why forced to use old versions? Updating is no hustle since node is fully backwards-compatible.

**Comment by revrng** [comment]
I think because bootstrap kickstart is used while development it's ok to drop old versions of node. 👍

**Comment by mischah** [comment]
@revrng Thanks for your feedback. Could you hit the 👍 within the top comment aka the issue description?

**Comment by mischah** [comment]
Makes the votes easier to grasp.

**Comment by chrkhl** [comment]
I think it's ok to drop support for old node versions.

**Comment by mischah** [comment]
Bye bye v4 and v5 🎉
