### ISSUE TITLE
Should we add info about adjusting ESLint and Stylelint settings to README?

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#174]
Do you think we should add information how to change ESLint and Stylelint settings to the README?

This might help people who aren’t used to work with these linters on a daily basis.

@micromata/ux Feedback appreciated

**Comment by krnlde** [comment]
Maybe just a link to their docs/examples?

**Comment by Anbe93** [comment]
Maybe just the really important once an the link
