### ISSUE TITLE
New name 😱

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#181]
I’ve created the following three PRs to check the potential new names:

# Baumeister

- Check the adapted [README](https://github.com/micromata/bootstrap-kickstart/blob/0178a222eb8eafd29a48c5f901629b49bc16b688/README.md)
- See #180 for the whole changeset

# KITT

- Check the adapted [README](https://github.com/micromata/bootstrap-kickstart/blob/c3b1ccbe2927010dab1be4d8c27389dac207303b/README.md)
- See #179 for the whole changeset

# Buildr

- Check the adapted [README](https://github.com/micromata/bootstrap-kickstart/blob/e22662e99b94c82020c7c214a8a9652513d5472e/README.md)
- See #178 for the whole changeset

Does Baumeister feel right? Or do you prefer one of the alternatives?

---

### Questions regarding the release:
Should we release Bootstrap Kickstart 4 as newName 4.0.0 or as newName 1.0.0?

In case of the latter: Should we keep the version history? Because we have to dump Git tags anyway.

**Comment by lfuelling** [comment]
Baumeister v1.0.0 🔥

**Comment by nicolaisueper** [comment]
I think 'Baumeister' is the best of the three options.

**Comment by revrng** [comment]
Hey,

great idea creating three prs to get a better feeling for the new name 👍 Baumeister feels good to me. But buildr is also a very nice fit! Good point with the versioning. Because we have projects relying on bootstrap kickstart 3.0, I think ist would be a good idea to keep the git history.

**Comment by mischah** [comment]
I’ve just merged #180 🎉 

**The questions regarding the release remain:**

Should we release Bootstrap Kickstart 4 as newName 4.0.0 or as newName 1.0.0?

In case of the latter: Should we keep the version history? Because we have to dump Git tags anyway.

**Comment by lfuelling** [comment]
I'd go with 1.0.0 

What exactly do you refer to as version history?
I would at least keep the commit log.

**Comment by nuz-y** [comment]
I prefer the englisch word "Buildr" instead of the german "Baumeister". But why do you open the Pandora's Box again? :)

**Comment by mischah** [comment]
Closing this.
- #180 is merged 
- we have a release strategy. See #183
