### ISSUE TITLE
Should we default to using handlebars?

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#184]
Hej,

right now we’re setting:

```javascript
export const useHandlebars = true;
```

by default. Should we keep that? 

Can I haz a 👍  or 👎 ?

**Comment by mischah** [comment]
Defaulting to use Handlebars means you have to change that in case you want to build a Single Page App.

The questions is also related to the default setting of the Yeoman Generator.

**Comment by lfuelling** [comment]
I like handlebars, so I'd say yes. 😄

**Comment by Anbe93** [comment]
I would say so, too. In the Yeoman-Generator I would add a question for that. Something like: "Would you like to build a awasome SPA?" And the answer would change it to false.

**Comment by krnlde** [comment]
I don't have an opinion on this, I go with the flow.

**Comment by Anbe93** [comment]
Just to be clear. Not any answer would change it to false 😂

**Comment by nicolaisueper** [comment]
Nah 😨

**Comment by mischah** [comment]
@Anbe93 

> I would say so, too. In the Yeoman-Generator I would add a question for that. Something like: "Would you like to build a awasome SPA?" And the answer would change it to false.

@nicolaisueper already has implemented that prompt with https://github.com/micromata/generator-bootstrap-kickstart/commit/0965d29381ad4e36bc68810c1183e0d4d3c1e125 😘

**Comment by mischah** [comment]
> I don't have an opinion on this, I go with the flow.

Me neither has a strong opinion. Tend to giving a 👍 though.

**Comment by mischah** [comment]
Thanks for the feedback. Going to keep using Handlebars as default for now.

Made it clearer in https://github.com/micromata/bootstrap-kickstart/commit/b964848b497a611ab97a03d40dde898f602f4c76 that this is optional.
