### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by amrography** [micromata/bootstrap-kickstart#187]
I have installed every thing with npm-install, no error was there. But when I run grunt serve it shows on the browser : Cannot GET / . The port of localhost is 9001

this is screen shot of project structure:
![screen shot 2017-06-15 at 2 26 42 pm](https://user-images.githubusercontent.com/9614340/27181331-75cad94c-51d7-11e7-9e92-847ddab3c313.png)

**Comment by nicolaisueper** [comment]
There seems to be neither a `dist` nor `server` folder present. Did you run `grunt dev` or simply `grunt` before?

**Comment by nicolaisueper** [comment]
The execution of `grunt` inside your project root should process and serve your sources

**Comment by amrography** [comment]
@nicolaisueper No, I didn't try it before. Server folder is present now. Thank you
