### ISSUE TITLE
Fatal error: Unexpected token P

### ISSUE THREAD

**Issue by benjamingb** [micromata/bootstrap-kickstart#23]
- When a change in the index.html is , you get this error "Fatal error: Unexpected token P" .
 - Nor styles are displayed

**Comment by krnlde** [comment]
Hey @benjamingb could you please provide a more detailed error message? Does the error appear in the browser console or in the terminal? Which browser + version do you use?

**Comment by mischah** [comment]
I’m closing this because we don’t have a chance to reproduce this error due to missing details in your description. 

Feel free to add additional information or at least a screenshot and I’ll reopen this issue.
