### ISSUE TITLE
Make use of includes for repeating elements like header, footer etc.

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#24]
Example: 
You have a project with 10 pages and every page shares elements like footer, header etc.
So If you want to change something in the footer you have to adapt the change in all of the 10 pages.

To avoid this you could make use of includes. This feature is provided by `grunt-processhtml`. We already use this task in the default bootstrap kickstart but we don’t use the include feature by default.

I think that would be a useful addition although it will increase complexity of the gruntfile because we need an additional directory (and corresponding tasks) to store the builded html to make the server task work.

Another negative connotation: The line numbers of the markup linters (htmllint and bootlint) won’t fit any longer, because we need to lint the combined files (with rendered includes) :disappointed:

**Comment by mischah** [comment]
Hi @krnlde :wave:

What to you think about the negative aspects of this enhancement?

**Comment by krnlde** [comment]
I didn't think of the linting issue so far, but it's a great point. Though, I use the include comment for headers and footers and didn't have any issues so far. Since The linter will also check the partials.

**Comment by mischah** [comment]
I don’t think linting the partials will work for the »HTML Lint« task.

It will throw errors because the HTML5 specs require:
+ a `<head>` element
+ a valid doctype
+ a `<title>` element within the `<header>`
+ a `<title>` element within the `<header>`
+ a `<meta charset="foobar" />` element within the `<header>` 
+ etc

But I  think wrong line numbers are less work intensive then »copy/pasting« or »find/replacing« changes on multiple templates. 

So I think we should use includes by default in this repo and use it in the Yeoman generator when people decide to use more boilerplate code.

**Comment by krnlde** [comment]
Agreed

**Comment by mischah** [comment]
Man you’re fast with your replies :boom:  :gun:

**Comment by krnlde** [comment]
I'm from the interwebs. What did you expect? :-P

**Comment by mischah** [comment]
:rocket: :laughing:

**Comment by mischah** [comment]
@krnlde Going to adress this issue with a simple static file generator called [grunt-generator](https://github.com/clavery/grunt-generator) which is much more powerful than `grunt-processhtml `:

The concept of file handling is similar to Jade by having:

- Templates
- Pages
- Partials

… but less mighty. It’s just using handlebars so you can:

- write plain HTML
- use build in helpers provided by handlebars
- go crazy with custom helpers :heart_eyes: 

Beside handlebars it’s possible to use Jekyll like frontmatters like:

    ---
    title: Sticky footer example
    template: default
    active: index
    key: value
    ---

These are available in the handlebars context via `{{page.key}}` so you can use them in the Markup and have fun with custom helpers (example: highlighting active pages in a navbar).

See [feature branch](https://github.com/micromata/bootstrap-kickstart/tree/feature/%2324).

**Comment by krnlde** [comment]
:+1:

**Comment by mischah** [comment]
Done in develop branch. Will make it into master in the next release.

**Comment by mfroehner** [comment]
Good Job! Release soon!
Von unterwegs gesendet

**Comment by mischah** [comment]
@mfroehner 
Will do that very soon. Currently documenting changes in the readme :kissing:
