### ISSUE TITLE
Bring back cachebusting (for js and css on production html files)

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#31]
We had that once upon a time for our dev files. Which caused some trouble and actually wasn’t needed, because you should simply disable chaching within the devtools (when they are open).

But how about adding this to html files in the `dist`directory? 
Need to figure that out …

**Comment by krnlde** [comment]
Consider https://github.com/sindresorhus/gulp-rev

**Comment by mischah** [comment]
Thanks, but aus long als we stick to Grunt I would prefer https://github.com/hollandben/grunt-cache-bust/ because it seems to be Vetter maintained than https://github.com/cbas/grunt-rev 

For Gulp I surely would take the task maintained by Sindre :unicorn: :octocat:

**Comment by mischah** [comment]
Pull Request over here: #104 :octocat:

**Comment by mischah** [comment]
Closed with #104
