### ISSUE TITLE
Need another module system for JS modules

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#32]
… and a module loader instead of using the [revealing module pattern](http://www.addyosmani.com/resources/essentialjsdesignpatterns/book/#revealingmodulepatternjavascript) relying on the global scope (even with using a namespace to prevent polluting the global scope).

Going to take a closer look at:
- browserify for using CommonJS modules
- SystemJS or ES6 Module Loader polyfill for using ES6 modules

Any thoughts on that @krnlde?

**Comment by krnlde** [comment]
Personally I like the way systemjs works. It's similar to the require.js workflow really. Plus it uses promises. Plus it's based on standards. I have no experience with browserify, though.

**Comment by mischah** [comment]
@krnlde Thanks Going to give it a try :+1:

**Comment by krnlde** [comment]
Angular is using system.js too.

**Comment by mischah** [comment]
After chatting with @revrng I came to the conclusion that now that ES6/7 is widely used we should use Babel and not just a module loader. 

So we can load modules and start exploring ES6 Features :kissing_heart:

**Comment by mischah** [comment]
> Preparing for ES6 modules? This rule forces you to use require() in a compatible way: http://eslint.org/docs/rules/global-require

**Comment by krnlde** [comment]
Di you know that System.js has the babel compiler as a transpile/parse step?

**Comment by mischah** [comment]
Nope. Still a bit confused about all the possibilities.

But this post really enlighted me:
[An Intro To Using npm and ES6 Modules for Front End Development](http://wesbos.com/javascript-modules/)

**Comment by revrng** [comment]
I found a nice article about setting up browserify and babel with grunt. Maybe we should give it a try!?
http://www.sitepoint.com/setting-up-es6-project-using-babel-browserify/

**Comment by mischah** [comment]
:+1:

**Comment by krnlde** [comment]
I'm using browserify in another project. I find it a bit slow but does its job very well. Try +1

**Comment by mischah** [comment]
@revrng I guess we can close this 😏

**Comment by krnlde** [comment]
Why?

**Comment by mischah** [comment]
Jep. It’s implemented with #86 which now is in develop branch :blush:
