### ISSUE TITLE
Get rid separate minified JS files in `dist`

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#36]
Until now we create minified versions of each and every JS file beside `built.min.js`.
Therefore `dist/assets/js` ends up being packed with files like:
```
base.min.js
built.min.js
moduleFoo.min.js
moduleBar.min.js
moduleFooBar.min.js
```

I don’t see any need for these files (besides `built.min.js` of course :relaxed: )

@krnlde Do you agree with getting rid of them?

**Comment by krnlde** [comment]
Yes, since for development we use the uncombined,  unminified sources.

**Comment by mischah** [comment]
Done in develop branch. Will make it into master in the next release. :kissing_heart:
