### ISSUE TITLE
Add files automagically to version control in release tasks

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#37]
Related to #29 

If you have new files in dist since last release the won’t be commited with the release because they are unknown for Git. 

Which leads to »refinish« a release by:

1. Deleting the Git tag pointing to your release tag
2. Adding the unknown files to Git
3. `git commit --amend`
4. Creating a knew tag pointing to the »new« release commit.

**Comment by krnlde** [comment]
Could be a problem when accidentally copying large files in the assets folder. You'll have a bad time removing them from the history.

**Comment by mischah** [comment]
I don’t agree because of the following to reasons:

# I know it sucks to »revert« a release. But it’s not that hard because we don’t merge a release commit automatically to the `master` branch nor we automatically push the changes to origin
# I think it happens more often that you have to refinish a release because of new files which are unknown to git (as described in the issue above) than you have to revert a release because you added unwanted files by accident.

**Comment by mischah** [comment]
Hej @krnlde,

I just read this [discussion](https://github.com/vojtajina/grunt-bump/pull/87) about exactly our usecase and your concerns. 

Bottom Line:
I think we should add files automatically but restrict files to add to the `dist`directory.
Because adding untracked files to Git is only needed for projects where we’ve added the `dist` directory to version control.
> My release tasks are generating files in my dist directory which is under version control.
When there are new files (which are already added and commited in my src directory) they are untracked in dist after running one of my release tasks.

**Comment by mischah** [comment]
Implemented in dev branch in c9fe1aa3978b68f6d6920015c9b1cc68b3c8f6d4. But as »opt in« change. Because it only makes sense when the `dist` folder is under version control. 

Improvement for the yeoman generator: An option like »Do you want to have your dist directory under version control« which will remove `dist` from `.gitignore` and activate the `gitadd` task.
