### ISSUE TITLE
Rename task `grunt server` 

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#39]
Rename `grunt server` to `grunt serve`. Former seems to be something like a »de facto standard«.

We could alias the old name to the new to avoid confusion :wink:

**Comment by krnlde** [comment]
thank you :)

**Comment by mischah** [comment]
Done in develop branch. Will make it into master in the next release. :kissing_heart:

**Comment by krnlde** [comment]
:shipit:

**Comment by mischah** [comment]
I hope to release v1.4.0 today :star2:
