### ISSUE TITLE
Switch to ESLint 

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#40]
I think the switch to [ESLint](http://eslint.org/) makes more sense than adding [JSCS](http://jscs.info/).

I guess @krnlde agrees :blush:

… but there is one thing I’m still considering. Should we:

- create (and maintain!) an own `.eslintrc` file
- load a [shared config](http://eslint.org/docs/developer-guide/shareable-configs.html) such as [eslint-config-standard](https://www.npmjs.com/package/eslint-config-standard), [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) or [eslint-config-xo](https://www.npmjs.com/package/eslint-config-xo)
- choose the most convenient way with [XOXO](https://github.com/sindresorhus/xo)

I would prefer the latter option because of simplicity. I personally prefer the same [code styles](https://gist.github.com/mischah/4276480) as @sindresorhus and believe that he will maintain a trustworthy config over here: https://github.com/sindresorhus/eslint-config-xo/blob/master/index.js

@krnlde Are you with me?

**Comment by krnlde** [comment]
I don't know sindres config in particular, but the move to eslint is essential. It has better guideline detection in addition to the linting, which I also find better. Plus the es6 linting which we are currently not using though. I have created my eslint file, and therfore coding guideline,  over the last month which I really like. Sometimes I feel pissed when another config stops me from being lean and creative just for the guideline's sake. 

For example my beloved one liner shortcut: `if (falsy)  return;` which, in most config is not allowed. 

But I guess this needs some discussion and I am totally willing to take one external maintained config, as long as we are concise in the particular project.

**Comment by krnlde** [comment]
Sorry for the bad English :D I am being actively autocorrected by my mobile.

**Comment by mischah** [comment]
hehe :smile: 

Thanks for the feedback.

My personal gist of it: You agree with using XOXO.

Cause the following isn’t a problem with XOXO:
> Sometimes I feel pissed when another config stops me from being lean and creative just for the guideline's sake.

We are able to Override any of the default rules. See Readme of XOXO: https://github.com/sindresorhus/xo#rules

Here you can see the defaults:
https://github.com/sindresorhus/eslint-config-xo/blob/master/index.js

**Comment by mischah** [comment]
@krnlde I just replaced JSHint with ESLint in the develop branch :_sparkling_heart:

But I decided against uxing XO as a wrapper for ESLint and only pull in the shared config from XO directly. See [package.json](https://github.com/micromata/bootstrap-kickstart/blob/develop/package.json#L24)

In our [.eslintrc](https://github.com/micromata/bootstrap-kickstart/blob/develop/.eslintrc) you can see how easy it is to override rules from [eslint-config-xo](https://github.com/sindresorhus/eslint-config-xo/blob/master/index.js)

**Comment by mischah** [comment]
Done in develop branch. Will make it into master in the next release.
