### ISSUE TITLE
How to handle Bootstrap variables with Bootstrap 4 

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#41]
### Short summary of the problem

We can’t use our variables.less to override Bootstrap variables in Bootstrap 4. Because Sass […] 

… to be continued. (Just a reminder for now)

**Comment by krnlde** [comment]
We have to rely on bootstrap's use of `!default`. If that works out great we can insert our "overrides" before the actual bootstrap, which would look like this:

```scss
@import 'bs_variables';
@import 'bootstrrap';
@import 'our_theme';
```

Right now the biggest problem is, that we are not able to change variables afterwards (retroactively). Once set and used, the value is bound to its property at that given time which is exactly the opposite how less' lazy-loaded variables work.

tbc.

**Comment by mischah** [comment]
@nicolaisueper Did you finish a demo setup in [v4-sass-dev](https://github.com/micromata/bootstrap-kickstart/tree/v4-sass-dev)?

**Comment by nicolaisueper** [comment]
I did, but I didn't pushed it yet, because I was busy learning some sass and trying out several plugins in combination with bootstrap 4. I think the sass setup will be done until thursday.

**Comment by mischah** [comment]
👌

**Comment by mischah** [comment]
Seems to work.
