### ISSUE TITLE
Include JS Unit Tests

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#43]
Add unit test boilerplate with the following stack:
- mocha (grunt-mocha-phantomjs vs. grunt-karma / karma-mocha)
- chai (using bdd 'expect' style)
- [blanket.js](https://github.com/alex-seville/blanket) for coverage

**Comment by revrng** [comment]
I just configured karma in a fun-project with ES6 code coverage by using isparta. This was a very helpful example-project: https://github.com/kt3k/karma-browserify-isparta-example. 

I think we should give it a try, looks very promising.

**Comment by mischah** [comment]
@revrng Removed the 3.0 milestone …
Planned for 4.x

**Comment by mischah** [comment]
We should use Jest:
+ API very similiar to Mocha
+ No globals
+ Built in coverage for ES6 
+ Slick CLI output

I’m sure @revrng can name a few additional pro arguments 😏

**Comment by mischah** [comment]
Made it with #1499be8 to the `v4-dev` branch. 🎉
