### ISSUE TITLE
Automagic generation of CSS Sprites

### ISSUE THREAD

**Issue by revrng** [micromata/bootstrap-kickstart#61]
Spritesmith seems to be a good library for this purpose:
https://github.com/Ensighten/grunt-spritesmith

**Comment by revrng** [comment]
Spritesmith seems to be a good library for this purpose:
https://github.com/Ensighten/grunt-spritesmith

**Comment by mischah** [comment]
Yeees :ok_hand:

**Comment by mischah** [comment]
I wonder how the default setup of this task should look like.

Because something like the following is too generic:

```javascript
sprite: {
  all: {
    src: 'path/to/your/sprites/*.png',
    dest: 'destination/of/spritesheet.png',
    destCss: 'destination/of/sprites.css'
  }
}
```

I guess settings for sprite generation are very project specific. So I guess we should use the following as default:

```javascript
sprite: {
  /*
   * Generating CSS sprites is very project specific. Please take your time and 
   * configure one ore more subtasks according to your needs.
   */
  // subTaskName: {
  //   src: 'path/to/your/images/*.png',
  //   dest: 'destination/of/spritesheet.png',
  //   destCss: 'destination/of/sprites.less'
  // }
}
```

Any thoughts on that @revrng?

**Comment by revrng** [comment]
That's a good point. Maybe we should write a few more lines how to use the sprite plugin. Especially how to integrate the generated sprites.less into the existing less files and how to use the generated sprite mixins.

**Comment by mischah** [comment]
Good catch. Makes sense to point out to https://github.com/Ensighten/grunt-spritesmith or add some own documentation about how to set up this thing.

I guess that belongs to the readme and we could add another sentence like »See readme for further information« or just »See https://github.com/Ensighten/grunt-spritesmith for further information«.

**Comment by mischah** [comment]
Going to close this (for now).

If we have a project using SVGs intensively we should consider using either [gulp-svg-sprite](https://github.com/jkphl/gulp-svg-sprite) or [gulp-svg-sprites](https://github.com/shakyshane/gulp-svg-sprites) and check if it makes sense to integrate one or another in Bootstrap Kickstart by default.

**Comment by mischah** [comment]
Going to reopen this just in case someone finds time to investigate those gulp plugins ⬆️

**Comment by mischah** [comment]
Closing this.
Issue might be recreated in the upcoming Baumeister Repo.
