### ISSUE TITLE
Perf improvements for builds

### ISSUE THREAD

**Issue by mischah** [micromata/bootstrap-kickstart#75]
We should consider which tools make sense to improve performance beside automatically generate CSS Sprites (#61)

Does it make sense to use a tool to inline above-the-fold CSS by default?
See above-the-fold CSS [Critical-path (Above-the-fold) CSS Tools](https://github.com/addyosmani/critical-path-css-tools)

Should we add a tool to benchmark and analyse performance?
See http://perf-tooling.today/tools?q=metrics 

Any suggestions welcome :octocat: 

//cc @krnlde @mfroehner @uschmidt @revrng @jMengel

**Comment by krnlde** [comment]
We should also consider @mpohl 's word on that. He used the kickstart recently and found some flaws as well as improvables.

**Comment by mischah** [comment]
@mpohl Feedback of any kind is highly appreciated :kissing_smiling_eyes:

**Comment by mischah** [comment]
Closing this. 
Issue might be recreated in the upcoming Baumeister Repo.
