### ISSUE TITLE
Error calling .postinstall.js script in package.json on Windows 7

### ISSUE THREAD

**Issue by odoell** [micromata/bootstrap-kickstart#82]
Calling the .postinstall.js script from node install produces an error on Windows 7 systems.
Because Windows doesn't recognize the shebang line in scripts and handles binaries with file endings associated programs. In this case (.js) with the Windows Scripting Host.

replacing the script configuration with:

```
"scripts": {
    "postinstall": "chmod u+x .postinstall.js && node ./.postinstall.js"
  }
```

it works again. The important thing here is adding 'node' before .postinstall.js, telling Windows explicit to use node.js to run the script.

Unfortunately i cannot confirm if this change breaks this on Linux or Mac Os systems.

Also read this article: [Writing cross-platform Node.js](http://shapeshed.com/writing-cross-platform-node/) scroll down until "Scripts in package.json", there is the problem also specified with my solution.

**Comment by mischah** [comment]
Cool. Never had the chance to check the whole thing in windows. Thanks :ok_hand: 

Going to check the impact on OS X very soon.

:octocat:

**Comment by mischah** [comment]
Thanks for reporting. Issue is fixed within the latest release.

**Comment by burak-sinikci** [comment]
I get the same error on Window 10

**Comment by mischah** [comment]
Weird. should be fixed since march.

Could you provide more details?

**Comment by odoell** [comment]
unfortunately i do not know the specific details how win10 handles all the node stuff. i had this problem before the fix with win 7

**Comment by odoell** [comment]
maybe node.js is not in his path... but more details would be helpful

**Comment by burak-sinikci** [comment]
i dont know if this correct, but with this changes i dont get errors

`"postinstall": "node ./.postinstall.js"`
