### ISSUE TITLE
Add tolerance to grunt-newer task

### ISSUE THREAD

**Issue by krnlde** [micromata/bootstrap-kickstart#89]
Due to the close of https://github.com/tschaub/grunt-newer/issues/86#event-625943070 we should add a `tolerance` of about 500ms (just a guess to be safe) for the windows users among us. Should have a huge perf. impact for them.

**Comment by mischah** [comment]
Is it a bug or an enhancement. I would say somethin’ in between 😆 
![report-surf-bolinas-Dw1m8lSxkXPZC](https://camo.githubusercontent.com/f804b2448d830d1ae4fee38d9ba3cfb755f84f10/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f4477316d386c53786b58505a432f67697068792e676966)

**Comment by krnlde** [comment]
Because they are unable to fix the bug in Windows (or they don't wanna) I'd say a compromise :D

**Comment by krnlde** [comment]
As https://github.com/tschaub/grunt-newer/issues/86#issuecomment-209809349 quoted a `tolerance: 1000` should solve the windows issue.

**Comment by mischah** [comment]
Fixed in develop branch. Will land in master and the next release very soon.

**Comment by krnlde** [comment]
wheeeee

**Comment by mischah** [comment]
Just released v2.2.0 ➡️ https://github.com/micromata/bootstrap-kickstart/releases/tag/2.2.0
