### ISSUE TITLE
Reduce bundle file-size

### ISSUE THREAD

**Issue by revrng** [micromata/bootstrap-kickstart#92]
Using browserify the file size of the bundle can be dramatically reduced by declaring frontend-dependencies like »bootstrap« or »jquery« as external. I think the already modified variant is used in this case. Maybe we should generally declare all dependencies as externally!? Maybe by parsing the dependencies property of the package.json? The other benefit is that the bundling will be faster, because external dependencies aka »vendors« are only bundled once.

**Comment by mischah** [comment]
Does declaring them as `external ` means you aren’t able to `import` them to use them in a es6 module way? 

I would like to get my hands into this to try to understand what browserify does with those vendor packages.

**Comment by revrng** [comment]
No. It's still possible to import those dependencies as usual. Only the result of the bundle is another. 
👍 Sounds good. I'll also continue to experiment with it.

**Comment by mischah** [comment]
I think I do understand now.

According to browserify docs `external` does the follwing:
> Prevent file from being loaded into the current bundle, instead referencing from another bundle.

I was still confused after reading this :smile:

But the following post enlighted me:
http://benclinkinbeard.com/posts/external-bundles-for-faster-browserify-builds/

**Comment by mischah** [comment]
Closed with the merge of #118
