### ISSUE TITLE
Error on build process

### ISSUE THREAD

**Issue by burak-sinikci** [micromata/bootstrap-kickstart#95]
I get this error and i dont know whats wrong?
I dont change anything.
```
Running "cssmin:bower" (cssmin) task
Warning: Path must be a string. Received undefined Use --force to continue.
```

**Comment by burak-sinikci** [comment]
Update the package from 1.0.1 to 1.0.2. That solved the problem.
`grunt-contrib-cssmin@1.0.2`

**Comment by mischah** [comment]
Related to #93
Trying to fix this tonight. Thanks for posting your »solution«

**Comment by mischah** [comment]
Fixed with the latest release.
